config/routes.rb
Rails.application.routes.draw do

   get '/login', to: 'sessions#new'
   post '/login', to: 'sessions#create'
   
   get '/signup', to: 'users#new'
   
   post '/signup', to: 'users#create'
   
   get '/', to: 'sessions#welcome'
   
   get 'authorized', to: 'sessions#page_requires_login'
   
   delete '/logout', to: 'sessions#destroy'
   
   get '/auth/github/callback', to: 'sessions#create'
   
   get '/search', to: 'songs#search'

   resources :parts
   resources :songs  do
      resources :lyrics 

   end

   end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lyric.rb
class Lyric < ApplicationRecord
    belongs_to  :song, optional: true
    belongs_to  :part 
end

app/models/part.rb
class Part < ApplicationRecord
    has_many :lyrics
    has_many :songs, through: :lyrics
end

app/models/song.rb
class Song < ApplicationRecord
    validates_presence_of :title
    belongs_to :user
    has_many :lyrics
    has_many :parts, through: :lyrics

    scope :search, -> (search) { where("LOWER(title) LIKE ?", "%#{search.downcase}%") }

  #   def self.search(search)
      
  #     self.where("title LIKE ?", "%#{search}%")
  # end 

  


end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :songs
    validates_presence_of :email, :password
    validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

helper_method :current_user
helper_method :logged_in?

  def login(user)
    session[:user_id] = @user.id
  end

private   
  def current_user    
  @user = User.find_by_id(session[:user_id]) if logged_in?
  end


  def logged_in?
     !!session[:user_id] 
  end
    
  def require_login
        redirect_to '/' unless logged_in?
     end
end

app/controllers/lyrics_controller.rb
class LyricsController < ApplicationController
  before_action :require_login
  before_action :get_song, only: [:new , :show]



 
 def new
    get_song
      @lyric = Lyric.new
  end
  
    
  def create
      @song = Song.find_by(id: params[:lyric][:song_id])
        @lyric = Lyric.new(lyric_params)
      if @lyric.save
        redirect_to song_lyric_path(@song, @lyric)
      else
        render :new
    end 
  end


  def show 
      get_song
      get_lyrics
      redirect_to song_lyric_path if !@song
  end 

  def edit
    get_song
    get_lyrics
  end

  def update
    get_song
    get_lyrics
    @lyric.update(lyric_params)
  redirect_to song_lyric_path(@song, @lyric)
  end


 private

 def get_song
  @song = Song.find_by(id: params[:song_id])
 end 

 def get_lyrics
  @lyric = Lyric.find(params[:id])
 end


def lyric_params
    params.require(:lyric).permit( :id, :song_id, :part_id, :count, :lyrics )
  end
end

app/controllers/parts_controller.rb
class PartsController < ApplicationController

    
  def index

    end
        
        
        
  def create     
  render :index   
  end
        
    private
  def parts_params
    params.require(:parts).permit(:part_id, :count, :genre, :song_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    @user = User.new
  end 
  
  def create
    if request.env["omniauth.auth"]
    if @user = User.find_by(github_uid: request.env["omniauth.auth"]["uid"])
     login(@user)
    redirect_to songs_path
     else
    @user = User.new(email: request.env["omniauth.auth"]["info"]["nickname"], github_uid: request.env["omniauth.auth"]["uid"], password: SecureRandom.hex)
    @user.save
    login(@user)
    redirect_to songs_path
  end

  else
   @user = User.find_by(email: params[:email])
   if !@user
    @error =" Account not found"
    render :new
   elsif !@user.authenticate(params[:password])
    @error =" please try again"
        render :new 
       
     else
      login(@user)
      redirect_to songs_path
     end
    end 
  end 

  def welcome 
   
  end 


  def destroy
  session.clear
  redirect_to songs_path
end 

private 
def auth
  request.env['omniauth.auth']
end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :require_login

  def index
    
    @songs = current_user.songs
   
  end

 
    def new
      @song = Song.new
      
    end



    def create
     
      @song = current_user.songs.build(song_params)

      if @song.save
      
        redirect_to new_song_lyric_path(@song)
      else
        render :new
    end
  end

  
  def show
    find_song
    if @song
      render :show
    else
      flash[:notice] = "Song not Found!"
      redirect_to songs_path
    end
  end


  def edit
    find_song
  end

  def search
    @songs = Song.search(params[:search])

    render :search
  end


  def update
    find_song
    @song.update(song_params)
    if @song.errors.empty?
      redirect_to @song
    else
      flash[:notice] = @song.errors.full_messages.join(" ")
      redirect_to edit_song_path(@song)
    end
  end

 

  def destroy
   find_song
    if @song.destroy
      redirect_to song_path
    else
      flash[:notice] = "Was unable to delete song!"
      redirect_to @song
    end
  end

  
  private
  
  def find_song 
    @song = Song.find_by(id: params[:id])
  end 
  
  def song_params
    params.require(:song).permit(:title, :genre, :user_id, :id)
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # skip_before_action :authorized, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      session[:user_id] = @user.id
      redirect_to new_song_path
   else 
    render :new
  end
end

  private
  def user_params 
    params.require(:user).permit(:password, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
end

app/helpers/sessions_helper.rb
module SessionsHelper

    def current_user    
        @user = User.find_by_id(session[:user_id]) if logged_in?
        end
        def logged_in?
            !!session[:user_id] 
        end
end

app/helpers/songs_helper.rb
module SongsHelper
    def format_count(count)
        words = count
        " your song currently has #{words} lyrics "
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.erb
<div class="header">
    <div class="title"> </div>
    <% if current_user %>
    <div class"email">
    <i>welcome, <%= current_user.email %></i>
    </div>
    <% end %>
    <div class="nav">
    
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SongBuilder</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if logged_in? %>
  <nav>
  Your Logged in !
  <%= link_to "log Out", logout_path, method: :delete%>
  </nav>
  <% else %>

<%= button_to "Login", '/login', method: :get%>
<%= button_to "Sign Up", '/signup', method: :get%>
<%= button_to('Log in with Github!', '/auth/github') %>
<%end%>
  <navbar>
  <%= render 'layouts/navbar' %>
  </navbar>
  <main class ="wrapper">
    <%= yield %>
    </main>
  </body>
</html>

app/views/lyrics/_form.html.erb
<%= form_for [@song, @lyric]  do |f|%>
<%= f.label :parts %>
   <div><%= f.collection_select :part_id, Part.all, :id, :category, prompt: true %></div> 
    <%= f.label :lyrics %><br>
   <div><%= f.text_area :lyrics%><br></div> 
    <%= f.label :count%><br>
 <div><%= f.text_area:count%><br></div>
    <%= f.hidden_field :user_id, value: current_user.id%>
    <%= f.hidden_field :song_id, value: @song.id %>
    <%= f.submit "Done"%>
    <%end%>

app/views/lyrics/edit.html.erb
<h1>
  Edit your lyrics!
</h1>


<%= render partial: 'form'%>

app/views/lyrics/new.html.erb
<h2> The lyrics to <%= @song.title %></h2>


<%= render partial:'/errors', locals: {record: @lyric } %> 

<%= render partial: 'form'%>

app/views/lyrics/show.html.erb
<h2> The lyrics to <%= @song.title %> </h2>
<%= link_to "Add new lyrics", new_song_lyric_path(@song) %> 

<br>

<%= link_to "Back", songs_path(@song), method: :get %>

<% @song.lyrics.each.with_index(1) do |lyric, index| %>
<h3><%= index %>. <%= lyric.part.category %></h3>
   <p> <%= lyric.lyrics %></p>
   <p><%= lyric.count %> lyrics</p>
   <%end%>

 <%= button_to "Edit Song!", edit_song_lyric_path(@song), method: :get %>

<%= button_to "Delete", @song , method: :delete, data: {confirm: "Are you sure you want to delete #{@song.title}"}%>

app/views/songs/_form.html.erb
  <%= form_for @song do |f|%>
    <%= f.label :title%><br>
    <%= f.text_field :title%><br>
    <%= f.label :genre %><br>
    <%= f.text_field :genre %><br>
    <%= f.hidden_field :user_id, value: current_user.id%>
    <%= f.submit %>
    <%end%>

app/views/songs/edit.html.erb
<h1>
  Edit your song!
</h1>
<%= render partial:'/errors', locals: {record: @song} %> 
<%= render partial: 'form'%>
 

app/views/songs/index.html.erb
<h2> Hello Artist ! The world is your canvas </h2>


<%= form_tag("/search", :method => "get") do %>
  <%= label_tag(:search, "Search:") %>
  <%= text_field_tag(:search) %>
  <%= submit_tag("search")%>
  <% end %>


  
  <br>
  <br>

  <%= button_to " Background Info (parts of a song)",parts_path %> 
  <br>
  <br>

  <%= link_to "Create a New Song!", new_song_path %>
  <br>
  <br>

  <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQojCc7qNks2-UKExoMXjMC7xXY2oup3c1HIw&usqp=CAU="250" height="500"">

  <% @songs.each do |s| %>
    <h4><a href="/songs/<%=s.id%>"><%=s.title %></a></h4>
  
    <p><%= s.lyrics.count %> parts</p>
    <% end %>

  <h3>
 
  
  </h3>
  
  
  




   

app/views/songs/new.html.erb
<h1>Write a song !</h1>
<%= render partial:'/errors', locals: {record: @song} %> 

      <%= render 'form', locals: {song_parts: @song} %> 
      <%= form_for @song do |f| %>
        <%= f.label :title %>
        <%= f.text_field :title %>
        <%= f.label :genre %>
        <%= f.text_field :genre %>
        <%= f.submit " Create and add lyrics" %>
        <% end %>

app/views/songs/search.html.erb
<%= form_with url:"/search", local: :true  do |form| %>
    <%= form.label "Search for:"%>
    <%= form.text_field :q%>
    <%= form.submit "Search"%>
  <% end %>
  
  <%= button_to "Back", songs_path(@song), method: :get %>



  <% @songs.each do |s| %>
    <h4><a href="/songs/<%=s.id%>"><%=s.title %></a></h4>   
    <p><%= s.lyrics.count %> lyrics</p>
    <% end %>

app/views/songs/show.html.erb
<h3><%=@song.title %></h3>
<h3><%=@song.genre %></h3>



    

<% @song.lyrics.each.with_index(1) do |lyric, index| %>
    <h3><%= index %>. <%= lyric.part.category %></h3>
       <p> <%= lyric.lyrics %></p>
       <p><%= lyric.count %> lyrics</p>
       <%end%>



    <%= button_to "Edit Song!", edit_song_path(@song), method: :get %>
    <%= button_to "Delete", @song , method: :delete, data: {confirm: "Are you sure you want to delete #{@song.title}"}%>

    <%= button_to "Back", songs_path(@song), method: :get %>

    </form>
  

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= render partial: '/errors', locals: { record: @user } %> 
<%= form_with model:@user, url: signup_path, local: :true do |f|%>
  <%= f.label :Email%><br>
  <%= f.text_field :email%><br>
  <%= f.label :password%><br>
  <%= f.password_field :password%><br>
  <%= f.submit %>
<%end%>